import test from 'node:test'; import assert from 'node:assert/strict';
import { createCollaborationContext } from '../src/collaboration/collaboration-context.ts';
import { validateCollaborationTextUpdate } from '../src/collaboration/update.ts';
import { CollaborationDocumentAdapter } from '../src/collaboration/document-adapter.ts';
import { BroadcastChannelCollaborationTransport } from '../src/collaboration/broadcast-channel-transport.ts';
const manifest={schema_version:1,source_fingerprint:'sha256:x',sections:[{id:'s',paragraphs:[{id:'p',text:'',style_ref:null,location:{section_index:0,paragraph_index:0}}],tables:[{id:'t',rows:[],cells:[{id:'c',text:'',style_ref:null,structure_readonly:true,location:{section_index:0,host_paragraph_index:1,control_index:0,cell_index:0,row_index:0,column_index:0}}],structure_readonly:true}]}],readonly_objects:[{id:'r',kind:'equation'}]};
const context=createCollaborationContext({getCollaborationManifest:()=>JSON.stringify(manifest)},'sha256:x');
const update={version:1 as const,updateId:'u1',documentFingerprint:'sha256:x',nodeId:'p',nodeKind:'paragraph' as const,text:'hello',clientId:'a',sequence:0};
test('context builds registry and update validator enforces node contract',()=>{ assert.equal(context.registry.get('p')?.kind,'paragraph'); assert.equal(validateCollaborationTextUpdate(update,context).text,'hello'); assert.throws(()=>validateCollaborationTextUpdate({...update,nodeKind:'cell'},context)); });
test('adapter routes paragraph updates and ignores duplicates',()=>{ let calls=0; const adapter=new CollaborationDocumentAdapter({applyCollaborationParagraphText:(_f,_s,_p,id)=>{calls++;return JSON.stringify({updated:true,kind:'paragraph',node_id:id})},applyCollaborationCellText:()=>''},context); assert.equal(adapter.applyRemoteUpdate(update),true); assert.equal(adapter.applyRemoteUpdate(update),false); assert.equal(calls,1); assert.equal(adapter.isApplyingRemoteUpdate,false); });
class FakeChannel { static all:FakeChannel[]=[]; listeners=new Set<(e:{data:unknown})=>void>(); closed=false; name:string; constructor(name:string){this.name=name;FakeChannel.all.push(this)} postMessage(data:unknown){for(const c of FakeChannel.all)if(c!==this&&c.name===this.name)for(const h of c.listeners)h({data})} close(){this.closed=true} addEventListener(_t:'message',h:(e:{data:unknown})=>void){this.listeners.add(h)} removeEventListener(_t:'message',h:(e:{data:unknown})=>void){this.listeners.delete(h)} }
test('broadcast transport ignores self and duplicate updates',()=>{FakeChannel.all=[];const factory=(n:string)=>new FakeChannel(n);const a=new BroadcastChannelCollaborationTransport('a',factory),b=new BroadcastChannelCollaborationTransport('b',factory);a.connect('s');b.connect('s');let count=0;b.subscribe(()=>count++);a.send(update);a.send(update);assert.equal(count,1);a.disconnect();b.disconnect();});
